version: "3.8"

volumes:
  pg_data:
  vscode_extensions:

services:
  db:
    restart: unless-stopped
    image: postgres:13.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    depends_on:
      - db
    build: 
      dockerfile: Dockerfile.prod
      context: .
    command:
      - sh
      - -c
      - gunicorn --bind=0.0.0.0:8000 developerstodaytest.wsgi:application
    ports:
      - 80:8000