# Generated by Django 3.1.5 on 2021-01-18 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20210118_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='post comment text')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation')),
                ('date_modified', models.DateTimeField(null=True, verbose_name='date of modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post comment author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='post.post')),
            ],
            options={
                'verbose_name': 'post comment',
                'verbose_name_plural': 'post comments',
                'ordering': ('-date_created',),
                'get_latest_by': ('-date_created',),
            },
        ),
    ]
