# Generated by Django 3.1.5 on 2021-01-18 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0005_auto_20210118_0526"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostUpvote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        related_query_name="post",
                        to="post.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="upvote user",
                    ),
                ),
            ],
            options={
                "verbose_name": "post upvote",
                "verbose_name_plural": "post upvotes",
                "ordering": ("-date_created",),
                "get_latest_by": ("-date_created",),
            },
        ),
    ]
